export const listOfcountry=[
    {
        values:"India",
        id:"1"
    },
    {
       values:"Russia",
       id:"2"
    },
    {
        values:"Thailand",
        id:"3"
    },
    {
       values:"Mexico",
       id:"4"
    },
    {
        values:"USA",
        id:"5"
    },
    {
       values:"France",
       id:"6"
    },
    {
        values:"Jordan",
        id:"7"
    },
    {
       values:"The Philippines",
       id:"8"
    },
]